# Measures unit and spec test coverage
{{> job-header.yml}}
steps:
  - attach_workspace:
      at: /tmp/coverage
  - run:
      name: Combine coverage reports
      command: |
        mkdir -p reports
        cp -R /tmp/coverage/* .
        npx istanbul-combine-updated coverage-*.json
  - run:
      name: Upload coverage
      command: bash <(curl -s https://codecov.io/bash)
